In [ ]:
#Install Numpy
!pip install numpy


In [ ]:
#import Numpy
import numpy as np


In [ ]:
#Creating numpy Array
arr = np.array([1,2,3,4,5])
print('Array :\n',arr)
print('Shape:',arr.shape)
print('Type:', type(arr))
print('Datatype:',arr.dtype)
print('Number of Dimensions:',arr.ndim)

Array :
 [1 2 3 4 5]
Shape: (5,)
Type: <class 'numpy.ndarray'>
Datatype: int64
Number of Dimensions: 1


In [ ]:
'''
ndarray -> N-Dimensional Array
'''

'\nndarray -> N-Dimensional Array\n'

In [ ]:
'''
Numpy arrary
'''

'\nNumpy arrary\n'

In [ ]:
#size Comparision
import sys

# Declaring a list of 1000 elements

S= range(1000)
#Output
print('size of each element of the list in bytes: ', sys.getsizeof(S))
print('size of the whole list in bytes: ', sys.getsizeof(S)*len(S))
#Declaring a numpy array of 1000 elements

D=np.arange(1000)
#output

print('\n size of each element fo the numpy array in the bytes :', D.itemsize)
print('size of the whole numpy array in bytes: ', D.size * D.itemsize)


size of each element of the list in bytes:  48
size of the whole list in bytes:  48000

 size of each element fo the numpy array in the bytes : 8
size of the whole numpy array in bytes:  8000


In [ ]:
#Numpy arrays are occupying 6 times less space than normal python arrays.
#Default starting value is 0 and step is 1

np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#np.arange(start,stop,step)
np.arange(1,10,1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(start=4,stop=100,step=2)

array([ 4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36,
       38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70,
       72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [ ]:
#Performance Comparision
#Import Time
import time

#size of array and lists
size = 1000000

#creating two lists
list1 = range(size)
list2 = range(size)

#creating two numpy arrays
array1 = np.arange(size)
array2 = np.arange(size)

#Capturing the time before multiplication
initialTime=time.time()

#Multipying the elements
res=[(a*b) for a, b in zip (list1,list2)]

#Capturing the time after the operation
print('Time taken for multiplication: ',(time.time()-initialTime) * 1000 ,'ms')


#Capturing the time before the operations.
initialTime=time.time()
#Multiplying the array.
res=array1 * array2
#Capturing the time after the operation
print('\nTime taken by numpy array: ',(time.time()-initialTime) * 1000 ,'ms')

Time taken for multiplication:  86.06791496276855 ms

Time taken by numpy array:  15.543937683105469 ms


In [ ]:
#Numpy arrays are homogeneous

arr=np.array([1,2.0,'Numpy'])
print('Array:',arr)
print('Data Type:',arr.dtype)

Array: ['1' '2.0' 'Numpy']
Data Type: <U32


In [ ]:
#Numpy arrays are homogeneous

arr=np.array([1,2.0,5.7])
print('Array:',arr)
print('Data Type:',arr.dtype)

Array: [1.  2.  5.7]
Data Type: float64


In [ ]:
#Random Module in Numpy

np.random.rand(3,4)

array([[0.50500035, 0.7015863 , 0.88395286, 0.00619061],
       [0.37471489, 0.5662307 , 0.2054104 , 0.47495448],
       [0.31488724, 0.37836423, 0.65043542, 0.78383242]])

In [ ]:
#np.random.randn() -> used to create an array of random values
#with mean=0 and standard deviation =1
np.random.randn(2,5)


array([[ 0.04293554,  0.28763066, -0.04631163,  0.04798008,  0.30453133],
       [ 1.19258764, -0.09103571,  0.0827043 ,  1.21522809, -0.58108752]])

In [ ]:
#np.random.randint (low,high,size)
np.random.randint(1,100,10)

array([36, 60,  5, 11, 60, 37,  6, 58,  7,  5])

In [ ]:
#np.random.randint (low,high,size)
np.random.randint(1,100,(3,5))

array([[74, 40, 95, 95, 80],
       [62, 28, 31, 63,  3],
       [96, 26, 57, 47, 87]])

In [ ]:
#High value is not included



In [ ]:
a=np.random.randint(1,100,(5,7))
print(a)

[[97 18  4 69  1 68 14]
 [84 74 56  8 95 83 83]
 [65 52 65  5 81 61 41]
 [50 86 15 56 82 46 12]
 [40 31 12 84 27 26 72]]


In [ ]:
#Accessing the elements by index
print(a[2,3])

5


In [ ]:
#Slicing along a single dimension

print(a[1:])

[[84 74 56  8 95 83 83]
 [65 52 65  5 81 61 41]
 [50 86 15 56 82 46 12]
 [40 31 12 84 27 26 72]]


In [ ]:
#Slicing along both dimensions.

print(a[1:,2:])

[[56  8 95 83 83]
 [65  5 81 61 41]
 [15 56 82 46 12]
 [12 84 27 26 72]]


In [ ]:
print(a[1:3,2:4])

[[56  8]
 [65  5]]
